# Generated by Django 4.2.5 on 2023-09-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Created',
            new_name='created',
        ),
    ]
